

TOPIC_SYNONYMS: dict[str, list[str]] = {
    "technology": [
        "tech",
        "software",
        "digital",
        "computer",
        "internet",
        "platform",
        "product",
        "startup",
        "innovation",
        "saas",
        "api",
        "cloud",
        "open source",
        "opensource",
    ],

    "programming": [
        "code",
        "coding",
        "developer",
        "developers",
        "development",
        "dev",
        "software engineering",
        "programming language",
        "python",
        "javascript",
        "typescript",
        "php",
        "java",
        "rust",
        "golang",
        "go language",
        "c#",
        "c++",
        "ruby",
        "kotlin",
        "swift",
        "dart",
        "elixir",
    ],

    "ai": [
        "artificial intelligence",
        "machine learning",
        "deep learning",
        "neural network",
        "neural networks",
        "large language model",
        "large language models",
        "llm",
        "llms",
        "gpt",
        "transformer",
        "transformers",
        "generative ai",
        "genai",
        "agent",
        "ai agent",
        "agents",
        "rag",
        "retrieval augmented generation",
        "embedding",
        "embeddings",
        "vector database",
        "vector db",
        "prompt engineering",
        "fine tuning",
        "fine-tuning",
        "inference",
        "model training",
    ],

    "web": [
        "web",
        "website",
        "frontend",
        "front-end",
        "backend",
        "back-end",
        "fullstack",
        "full-stack",
        "html",
        "css",
        "sass",
        "javascript",
        "typescript",
        "react",
        "vue",
        "vue.js",
        "angular",
        "svelte",
        "next.js",
        "nuxt",
        "astro",
        "node",
        "node.js",
        "express",
        "fastapi",
        "django",
        "flask",
        "symfony",
        "laravel",
    ],

    "frontend": [
        "frontend",
        "front-end",
        "ui",
        "ux",
        "design system",
        "component",
        "components",
        "css",
        "sass",
        "tailwind",
        "bootstrap",
        "react",
        "vue",
        "vue.js",
        "svelte",
        "angular",
        "next.js",
        "nuxt",
        "vite",
        "web components",
        "accessibility",
        "a11y",
    ],

    "backend": [
        "backend",
        "back-end",
        "api",
        "rest api",
        "graphql",
        "server",
        "database",
        "sql",
        "postgresql",
        "postgres",
        "mysql",
        "mariadb",
        "sqlite",
        "redis",
        "queue",
        "worker",
        "microservice",
        "microservices",
        "authentication",
        "authorization",
        "jwt",
        "oauth",
        "fastapi",
        "django",
        "flask",
        "symfony",
        "laravel",
        "spring",
    ],

    "devops": [
        "devops",
        "docker",
        "container",
        "containers",
        "kubernetes",
        "k8s",
        "ci",
        "cd",
        "ci/cd",
        "github actions",
        "gitlab ci",
        "deployment",
        "deploy",
        "infrastructure",
        "terraform",
        "ansible",
        "linux",
        "nginx",
        "apache",
        "monitoring",
        "observability",
        "prometheus",
        "grafana",
        "logging",
    ],

    "cloud": [
        "cloud",
        "aws",
        "amazon web services",
        "azure",
        "google cloud",
        "gcp",
        "serverless",
        "lambda",
        "cloudflare",
        "vercel",
        "netlify",
        "scaleway",
        "ovh",
        "infomaniak",
        "docker",
        "kubernetes",
        "storage",
        "cdn",
    ],

    "cybersecurity": [
        "security",
        "cybersecurity",
        "cyber security",
        "vulnerability",
        "vulnerabilities",
        "exploit",
        "malware",
        "ransomware",
        "phishing",
        "zero day",
        "zero-day",
        "cve",
        "patch",
        "breach",
        "data breach",
        "authentication",
        "authorization",
        "encryption",
        "privacy",
        "owasp",
    ],

    "data": [
        "data",
        "database",
        "dataset",
        "datasets",
        "data engineering",
        "data science",
        "analytics",
        "etl",
        "elt",
        "pipeline",
        "data pipeline",
        "warehouse",
        "data warehouse",
        "lakehouse",
        "spark",
        "pandas",
        "numpy",
        "sql",
        "postgresql",
        "bigquery",
        "snowflake",
    ],

    "open_source": [
        "open source",
        "opensource",
        "free software",
        "foss",
        "gnu",
        "linux",
        "github",
        "gitlab",
        "license",
        "mit license",
        "apache license",
        "gpl",
        "community",
        "maintainer",
        "contributors",
    ],

    "product": [
        "product",
        "productivity",
        "saas",
        "startup",
        "founder",
        "growth",
        "roadmap",
        "feature",
        "features",
        "release",
        "changelog",
        "user experience",
        "ux",
        "product management",
        "pm",
    ],

    "tools": [
        "tool",
        "tools",
        "developer tool",
        "developer tools",
        "devtool",
        "devtools",
        "cli",
        "sdk",
        "api",
        "framework",
        "library",
        "package",
        "extension",
        "plugin",
        "ide",
        "vscode",
        "visual studio code",
    ],
}